// Types
export interface Permission {
  id: string;
  name: string;
  actions: string;
  productCategory: string;
  taskCategory: string;
  actionType: string;
  sensitivityLevel: string;
  description: string;
  roleAccess: Record<string, string>;
}

export interface RoleDetails {
  description: string;
  canDo: string[];
  cannotDo: string[];
  bestFor: string;
}

export interface Role {
  id: string;
  name: string;
  category: string;
  details?: RoleDetails;
  userCount: number;
}

export interface RoleCategory {
  name: string;
  roles: Role[];
}

// Role details from CSV
const roleDetailsMap: Record<string, RoleDetails> = {
  super_admin: {
    description: "This role is assigned to the creator of a business account and should only be assigned to users who are allowed to perform all privileged actions. Only a Super Administrator can assign the Super Administrator role to other team members.",
    canDo: [
      "All Administrator capabilities",
      "Assign Super Administrator role to others",
      "Full account control",
      "Manage all team members and roles",
      "Access all account data and settings"
    ],
    cannotDo: [
      "Cannot change the account owner (only the owner can transfer ownership)"
    ],
    bestFor: "Account creator, C-level executives who need absolute control. High security risk if compromised."
  },
  admin: {
    description: "Full access to the account with the ability to manage all settings and perform all actions.",
    canDo: [
      "Manage all aspects of the account",
      "Invite and manage team members",
      "View and edit all financial data",
      "Configure account settings",
      "Access API keys and webhooks",
      "Manage disputes and refunds"
    ],
    cannotDo: [
      "Cannot assign Super Administrator role",
      "Cannot delete the account"
    ],
    bestFor: "Account owners, senior management who need complete control"
  },
  developer: {
    description: "Access to view and manage technical integration settings.",
    canDo: [
      "View API keys and create restricted keys",
      "Access webhooks and logs",
      "Test in sandbox mode",
      "View documentation",
      "Access developer tools",
      "View payment data"
    ],
    cannotDo: [
      "Cannot manage team members",
      "Cannot edit business settings",
      "Cannot process refunds",
      "Cannot access sensitive financial reports"
    ],
    bestFor: "Engineering teams building and maintaining integrations"
  },
  analyst: {
    description: "Read-only access to reports and data across the account.",
    canDo: [
      "View all reports and analytics",
      "Export data",
      "View payment and customer information",
      "Access financial reports",
      "View balance and payout information"
    ],
    cannotDo: [
      "Cannot make any changes",
      "Cannot process refunds",
      "Cannot edit customers or payments",
      "Cannot access API keys"
    ],
    bestFor: "Finance teams, business analysts, executives who need visibility"
  },
  support: {
    description: "This role is for people who need to refund payments, resolve disputes, and may need to update products.",
    canDo: [
      "View customer details",
      "View payment information",
      "Create and manage refunds",
      "View and respond to disputes",
      "Issue credit notes",
      "View subscriptions and invoices",
      "Update products"
    ],
    cannotDo: [
      "Cannot access API keys",
      "Cannot manage team members",
      "Cannot change account settings",
      "Cannot access detailed financial reports"
    ],
    bestFor: "Customer support teams handling day-to-day customer issues"
  },
  support_associate: {
    description: "Limited support access for basic customer inquiries.",
    canDo: [
      "View customer information",
      "View payment details",
      "View subscriptions and invoices",
      "View disputes (read-only)"
    ],
    cannotDo: [
      "Cannot process refunds",
      "Cannot manage disputes",
      "Cannot edit customer data",
      "Cannot access API keys"
    ],
    bestFor: "Junior support staff handling basic inquiries"
  },
  view_only: {
    description: "Read-only access to most parts of the Dashboard.",
    canDo: [
      "View payments and customers",
      "View basic reports",
      "View product and subscription data",
      "View disputes"
    ],
    cannotDo: [
      "Cannot make any changes",
      "Cannot process refunds",
      "Cannot export data in bulk",
      "Cannot access API keys",
      "Cannot view sensitive financial data"
    ],
    bestFor: "Team members who need visibility without ability to make changes"
  },
  dispute_analyst: {
    description: "Specialized access for managing disputes and chargebacks.",
    canDo: [
      "View and manage disputes",
      "Upload evidence",
      "Accept or challenge disputes",
      "View dispute analytics",
      "Access Radar for fraud prevention"
    ],
    cannotDo: [
      "Cannot process refunds outside of disputes",
      "Cannot manage customers",
      "Cannot access API keys",
      "Cannot manage team members"
    ],
    bestFor: "Fraud and risk teams focused on dispute management"
  },
  refund_analyst: {
    description: "Specialized access for processing refunds.",
    canDo: [
      "View payments and charges",
      "Create full and partial refunds",
      "View customer information",
      "View refund history"
    ],
    cannotDo: [
      "Cannot manage disputes",
      "Cannot access API keys",
      "Cannot manage subscriptions",
      "Cannot access financial reports",
      "Cannot manage team members"
    ],
    bestFor: "Finance operations teams focused on refund processing"
  },
  identity_analyst: {
    description: "Specialized access for identity verification and KYC.",
    canDo: [
      "View and verify identity documents",
      "Manage KYC workflows",
      "Review verification sessions",
      "Access compliance data"
    ],
    cannotDo: [
      "Cannot access payment information",
      "Cannot process refunds",
      "Cannot manage team members",
      "Cannot access API keys"
    ],
    bestFor: "Compliance and KYC teams managing identity verification"
  },
  tax_analyst: {
    description: "Specialized access for tax reporting and compliance.",
    canDo: [
      "View tax reports",
      "Manage tax settings",
      "Download tax documents",
      "Configure tax automation",
      "Access 1099 and tax ID information"
    ],
    cannotDo: [
      "Cannot access general financial reports",
      "Cannot process payments",
      "Cannot manage team members",
      "Cannot access API keys"
    ],
    bestFor: "Tax and accounting teams managing tax compliance"
  },
  iam_admin: {
    description: "Specialized access for managing team access and security.",
    canDo: [
      "Manage team members and roles",
      "Configure SSO and SAML",
      "Manage security settings",
      "Set up two-factor authentication",
      "View audit logs"
    ],
    cannotDo: [
      "Cannot access financial data",
      "Cannot process payments",
      "Cannot view customer PII",
      "Cannot access API keys for integrations"
    ],
    bestFor: "Security and IT teams managing access control"
  },
  issuing_support_agent: {
    description: "Specialized access for managing Issuing cards and cardholders.",
    canDo: [
      "View and manage issuing cards",
      "View cardholder information",
      "Manage card disputes",
      "View card transactions",
      "Update card status"
    ],
    cannotDo: [
      "Cannot access general payment data",
      "Cannot manage team members",
      "Cannot access API keys",
      "Cannot access non-Issuing products"
    ],
    bestFor: "Support teams focused on card issuing operations"
  },
  sandbox_admin: {
    description: "Full administrative access to sandbox/test environments only.",
    canDo: [
      "Full access to sandbox mode",
      "Create test data",
      "Access sandbox API keys",
      "Test integrations",
      "Invite sandbox users"
    ],
    cannotDo: [
      "Cannot access production data",
      "Cannot affect live transactions",
      "Cannot access production API keys"
    ],
    bestFor: "Developers and QA teams testing integrations"
  },
};

// Fake user counts for a ~100 user account
const userCounts: Record<string, number> = {
  super_admin: 2,
  admin: 4,
  iam_admin: 1,
  developer: 12,
  analyst: 8,
  dispute_analyst: 3,
  refund_analyst: 4,
  support: 18,
  support_associate: 15,
  view_only: 7,
  issuing_support_agent: 3,
  tax_analyst: 2,
  identity_analyst: 2,
  sandbox_admin: 5,
};

// Helper to add details to role
const withDetails = (id: string, name: string, category: string): Role => ({
  id,
  name,
  category,
  details: roleDetailsMap[id],
  userCount: userCounts[id] ?? 0,
});

// Role categories with display names
export const roleCategories: RoleCategory[] = [
  {
    name: "Admin",
    roles: [
      withDetails("super_admin", "Super administrator", "Admin"),
      withDetails("admin", "Administrator", "Admin"),
      withDetails("iam_admin", "IAM Admin", "Admin"),
    ],
  },
  {
    name: "Developer",
    roles: [
      withDetails("developer", "Developer", "Developer"),
    ],
  },
  {
    name: "Payments",
    roles: [
      withDetails("analyst", "Analyst", "Payments"),
      withDetails("dispute_analyst", "Dispute analyst", "Payments"),
      withDetails("refund_analyst", "Refund analyst", "Payments"),
    ],
  },
  {
    name: "Support",
    roles: [
      withDetails("support", "Support specialist", "Support"),
      withDetails("support_associate", "Support associate", "Support"),
    ],
  },
  {
    name: "Specialists",
    roles: [
      withDetails("issuing_support_agent", "Issuing support agent", "Specialists"),
      withDetails("tax_analyst", "Tax analyst", "Specialists"),
      withDetails("identity_analyst", "Identity analyst", "Specialists"),
    ],
  },
  {
    name: "View only",
    roles: [
      withDetails("view_only", "View only", "View only"),
    ],
  },
  {
    name: "Sandbox",
    roles: [
      withDetails("sandbox_admin", "Sandbox administrator", "Sandbox"),
    ],
  },
];

// All roles flattened
export const allRoles: Role[] = roleCategories.flatMap((cat) => cat.roles);

// Permission data from CSV
export const permissions: Permission[] = [
  {
    id: "account_admin_management_operations_1",
    name: "account_admin_management_operations",
    actions: "write",
    productCategory: "Account & Connect",
    taskCategory: "Manage team access",
    actionType: "Destructive",
    sensitivityLevel: "Non-sensitive",
    description: "Full administrative account management",
    roleAccess: { super_admin: "write", admin: "write", developer: "write" },
  },
  {
    id: "account_admin_management_operations_2",
    name: "account_admin_management_operations",
    actions: "write",
    productCategory: "Account & Connect",
    taskCategory: "Configure settings",
    actionType: "Destructive",
    sensitivityLevel: "Non-sensitive",
    description: "Full administrative account management",
    roleAccess: { super_admin: "write", admin: "write", developer: "write" },
  },
  {
    id: "account_operations_1",
    name: "account_operations",
    actions: "read, write",
    productCategory: "Account & Connect",
    taskCategory: "Configure settings",
    actionType: "Read + Write",
    sensitivityLevel: "Non-sensitive",
    description: "Read access to base account details",
    roleAccess: { super_admin: "write", admin: "write", view_only: "read", support: "write", support_associate: "write", analyst: "read", refund_analyst: "read", sandbox_admin: "read" },
  },
  {
    id: "account_operations_2",
    name: "account_operations",
    actions: "read, write",
    productCategory: "Account & Connect",
    taskCategory: "Monitor platform",
    actionType: "Read + Write",
    sensitivityLevel: "Non-sensitive",
    description: "Read access to base account details",
    roleAccess: { super_admin: "write", admin: "write", view_only: "read", support: "write", support_associate: "write", analyst: "read", refund_analyst: "read", sandbox_admin: "read" },
  },
  {
    id: "accounts_kyc_basic_1",
    name: "accounts_kyc_basic",
    actions: "read",
    productCategory: "Account & Connect",
    taskCategory: "Verify identity",
    actionType: "Read-only",
    sensitivityLevel: "Contains PII",
    description: "Read access to basic KYC fields",
    roleAccess: { super_admin: "read", admin: "read", view_only: "read", identity_analyst: "read" },
  },
  {
    id: "accounts_kyc_basic_2",
    name: "accounts_kyc_basic",
    actions: "read",
    productCategory: "Account & Connect",
    taskCategory: "Handle customer issues",
    actionType: "Read-only",
    sensitivityLevel: "Contains PII",
    description: "Read access to basic KYC fields",
    roleAccess: { super_admin: "read", admin: "read", view_only: "read", identity_analyst: "read" },
  },
  {
    id: "application_fee_operations_1",
    name: "application_fee_operations",
    actions: "read, write",
    productCategory: "Account & Connect",
    taskCategory: "Monitor platform",
    actionType: "Read + Write",
    sensitivityLevel: "Financial data",
    description: "Application fees for platforms",
    roleAccess: { super_admin: "write", admin: "write", view_only: "read", support: "write", analyst: "write" },
  },
  {
    id: "application_fee_operations_2",
    name: "application_fee_operations",
    actions: "read, write",
    productCategory: "Account & Connect",
    taskCategory: "Export & analyze data",
    actionType: "Read + Write",
    sensitivityLevel: "Financial data",
    description: "Application fees for platforms",
    roleAccess: { super_admin: "write", admin: "write", view_only: "read", support: "write", analyst: "write" },
  },
  {
    id: "connect_settings_1",
    name: "connect_settings",
    actions: "write",
    productCategory: "Account & Connect",
    taskCategory: "Configure settings",
    actionType: "Administrative",
    sensitivityLevel: "Non-sensitive",
    description: "Manage Connect settings",
    roleAccess: { super_admin: "write", admin: "write", support: "write", support_associate: "write" },
  },
  {
    id: "connect_settings_2",
    name: "connect_settings",
    actions: "write",
    productCategory: "Account & Connect",
    taskCategory: "Monitor platform",
    actionType: "Administrative",
    sensitivityLevel: "Non-sensitive",
    description: "Manage Connect settings",
    roleAccess: { super_admin: "write", admin: "write", support: "write", support_associate: "write" },
  },
  {
    id: "connected_account_operations_1",
    name: "connected_account_operations",
    actions: "read, write",
    productCategory: "Account & Connect",
    taskCategory: "Monitor platform",
    actionType: "Read + Write",
    sensitivityLevel: "Contains PII",
    description: "Connected accounts management",
    roleAccess: { super_admin: "write", admin: "write", view_only: "read", developer: "write", support: "write", support_associate: "write", analyst: "read" },
  },
  {
    id: "connected_account_operations_2",
    name: "connected_account_operations",
    actions: "read, write",
    productCategory: "Account & Connect",
    taskCategory: "Handle customer issues",
    actionType: "Read + Write",
    sensitivityLevel: "Contains PII",
    description: "Connected accounts management",
    roleAccess: { super_admin: "write", admin: "write", view_only: "read", developer: "write", support: "write", support_associate: "write", analyst: "read" },
  },
  {
    id: "embeddable_key_admin_1",
    name: "embeddable_key_admin",
    actions: "write",
    productCategory: "Account & Connect",
    taskCategory: "Configure settings",
    actionType: "Administrative",
    sensitivityLevel: "Payment credentials",
    description: "Embeddable keys admin",
    roleAccess: { super_admin: "write", admin: "write" },
  },
  {
    id: "embeddable_key_admin_2",
    name: "embeddable_key_admin",
    actions: "write",
    productCategory: "Account & Connect",
    taskCategory: "Develop & integrate",
    actionType: "Administrative",
    sensitivityLevel: "Payment credentials",
    description: "Embeddable keys admin",
    roleAccess: { super_admin: "write", admin: "write" },
  },
  {
    id: "sandbox_creation_1",
    name: "sandbox_creation",
    actions: "write",
    productCategory: "Account & Connect",
    taskCategory: "Develop & integrate",
    actionType: "Create & update",
    sensitivityLevel: "Non-sensitive",
    description: "Create sandbox organizations",
    roleAccess: { super_admin: "write", admin: "write", developer: "write", sandbox_admin: "write" },
  },
  {
    id: "team_management_1",
    name: "team_management",
    actions: "read, write",
    productCategory: "Account & Connect",
    taskCategory: "Manage team access",
    actionType: "Administrative",
    sensitivityLevel: "Non-sensitive",
    description: "Manage team members and roles",
    roleAccess: { super_admin: "write", admin: "write", view_only: "read", iam_admin: "write" },
  },
  {
    id: "team_management_2",
    name: "team_management",
    actions: "read, write",
    productCategory: "Account & Connect",
    taskCategory: "Configure settings",
    actionType: "Administrative",
    sensitivityLevel: "Non-sensitive",
    description: "Manage team members and roles",
    roleAccess: { super_admin: "write", admin: "write", view_only: "read", iam_admin: "write" },
  },
  {
    id: "sensitive_resources_1",
    name: "sensitive_resources",
    actions: "read",
    productCategory: "Admin",
    taskCategory: "Develop & integrate",
    actionType: "Read-only",
    sensitivityLevel: "Payment credentials",
    description: "API keys and secrets",
    roleAccess: { super_admin: "read", admin: "read", view_only: "read", developer: "read" },
  },
  {
    id: "sensitive_resources_2",
    name: "sensitive_resources",
    actions: "read",
    productCategory: "Admin",
    taskCategory: "Configure settings",
    actionType: "Read-only",
    sensitivityLevel: "Payment credentials",
    description: "API keys and secrets",
    roleAccess: { super_admin: "read", admin: "read", view_only: "read", developer: "read" },
  },
  {
    id: "billing_operations_1",
    name: "billing_operations",
    actions: "read, write",
    productCategory: "Billing & Subscriptions",
    taskCategory: "Manage billing",
    actionType: "Read + Write",
    sensitivityLevel: "Financial data",
    description: "Billing meters and bills",
    roleAccess: { super_admin: "write", admin: "write", view_only: "read", developer: "write", analyst: "write" },
  },
  {
    id: "billing_operations_2",
    name: "billing_operations",
    actions: "read, write",
    productCategory: "Billing & Subscriptions",
    taskCategory: "Export & analyze data",
    actionType: "Read + Write",
    sensitivityLevel: "Financial data",
    description: "Billing meters and bills",
    roleAccess: { super_admin: "write", admin: "write", view_only: "read", developer: "write", analyst: "write" },
  },
  {
    id: "billing_settings_operations_1",
    name: "billing_settings_operations",
    actions: "read, write",
    productCategory: "Billing & Subscriptions",
    taskCategory: "Configure settings",
    actionType: "Administrative",
    sensitivityLevel: "Non-sensitive",
    description: "Billing settings and profiles",
    roleAccess: { super_admin: "write", admin: "write", view_only: "read", developer: "write", support: "write", support_associate: "write", analyst: "write", refund_analyst: "read", dispute_analyst: "read" },
  },
  {
    id: "billing_settings_operations_2",
    name: "billing_settings_operations",
    actions: "read, write",
    productCategory: "Billing & Subscriptions",
    taskCategory: "Manage billing",
    actionType: "Administrative",
    sensitivityLevel: "Non-sensitive",
    description: "Billing settings and profiles",
    roleAccess: { super_admin: "write", admin: "write", view_only: "read", developer: "write", support: "write", support_associate: "write", analyst: "write", refund_analyst: "read", dispute_analyst: "read" },
  },
  {
    id: "credit_note_operations_1",
    name: "credit_note_operations",
    actions: "read, write",
    productCategory: "Billing & Subscriptions",
    taskCategory: "Handle customer issues",
    actionType: "Read + Write",
    sensitivityLevel: "Financial data",
    description: "Manage credit notes",
    roleAccess: { super_admin: "write", admin: "write", view_only: "read", developer: "write", support: "write", support_associate: "write", analyst: "write", refund_analyst: "write" },
  },
  {
    id: "credit_note_operations_2",
    name: "credit_note_operations",
    actions: "read, write",
    productCategory: "Billing & Subscriptions",
    taskCategory: "Manage billing",
    actionType: "Read + Write",
    sensitivityLevel: "Financial data",
    description: "Manage credit notes",
    roleAccess: { super_admin: "write", admin: "write", view_only: "read", developer: "write", support: "write", support_associate: "write", analyst: "write", refund_analyst: "write" },
  },
  {
    id: "invoice_operations_1",
    name: "invoice_operations",
    actions: "read, write",
    productCategory: "Billing & Subscriptions",
    taskCategory: "Handle customer issues",
    actionType: "Read + Write",
    sensitivityLevel: "Financial data",
    description: "Manage invoices and quotes",
    roleAccess: { super_admin: "write", admin: "write", view_only: "read", developer: "write", support: "write", support_associate: "write", analyst: "write", refund_analyst: "read", dispute_analyst: "read" },
  },
  {
    id: "invoice_operations_2",
    name: "invoice_operations",
    actions: "read, write",
    productCategory: "Billing & Subscriptions",
    taskCategory: "Manage billing",
    actionType: "Read + Write",
    sensitivityLevel: "Financial data",
    description: "Manage invoices and quotes",
    roleAccess: { super_admin: "write", admin: "write", view_only: "read", developer: "write", support: "write", support_associate: "write", analyst: "write", refund_analyst: "read", dispute_analyst: "read" },
  },
  {
    id: "invoice_operations_3",
    name: "invoice_operations",
    actions: "read, write",
    productCategory: "Billing & Subscriptions",
    taskCategory: "Export & analyze data",
    actionType: "Read + Write",
    sensitivityLevel: "Financial data",
    description: "Manage invoices and quotes",
    roleAccess: { super_admin: "write", admin: "write", view_only: "read", developer: "write", support: "write", support_associate: "write", analyst: "write", refund_analyst: "read", dispute_analyst: "read" },
  },
  {
    id: "subscription_operations_1",
    name: "subscription_operations",
    actions: "read, write",
    productCategory: "Billing & Subscriptions",
    taskCategory: "Handle customer issues",
    actionType: "Read + Write",
    sensitivityLevel: "Financial data",
    description: "Manage subscriptions",
    roleAccess: { super_admin: "write", admin: "write", view_only: "read", developer: "write", support: "write", support_associate: "write", analyst: "write", refund_analyst: "read", dispute_analyst: "read" },
  },
  {
    id: "subscription_operations_2",
    name: "subscription_operations",
    actions: "read, write",
    productCategory: "Billing & Subscriptions",
    taskCategory: "Manage billing",
    actionType: "Read + Write",
    sensitivityLevel: "Financial data",
    description: "Manage subscriptions",
    roleAccess: { super_admin: "write", admin: "write", view_only: "read", developer: "write", support: "write", support_associate: "write", analyst: "write", refund_analyst: "read", dispute_analyst: "read" },
  },
  {
    id: "capital_operations_1",
    name: "capital_operations",
    actions: "read, write",
    productCategory: "Capital & Treasury",
    taskCategory: "Monitor financials",
    actionType: "Read + Write",
    sensitivityLevel: "Financial data",
    description: "Capital for Platforms",
    roleAccess: { super_admin: "write", admin: "write", view_only: "read", developer: "write", analyst: "write" },
  },
  {
    id: "capital_operations_2",
    name: "capital_operations",
    actions: "read, write",
    productCategory: "Capital & Treasury",
    taskCategory: "Export & analyze data",
    actionType: "Read + Write",
    sensitivityLevel: "Financial data",
    description: "Capital for Platforms",
    roleAccess: { super_admin: "write", admin: "write", view_only: "read", developer: "write", analyst: "write" },
  },
  {
    id: "treasury_operations_1",
    name: "treasury_operations",
    actions: "read, write",
    productCategory: "Capital & Treasury",
    taskCategory: "Monitor financials",
    actionType: "Read + Write",
    sensitivityLevel: "Financial data",
    description: "Treasury financial accounts",
    roleAccess: { super_admin: "write", admin: "write", view_only: "read", analyst: "read" },
  },
  {
    id: "treasury_operations_2",
    name: "treasury_operations",
    actions: "read, write",
    productCategory: "Capital & Treasury",
    taskCategory: "Export & analyze data",
    actionType: "Read + Write",
    sensitivityLevel: "Financial data",
    description: "Treasury financial accounts",
    roleAccess: { super_admin: "write", admin: "write", view_only: "read", analyst: "read" },
  },
  {
    id: "identity_verification_operations_1",
    name: "identity_verification_operations",
    actions: "read, write",
    productCategory: "Compliance & Identity",
    taskCategory: "Verify identity",
    actionType: "Read + Write",
    sensitivityLevel: "Contains PII",
    description: "Identity verification",
    roleAccess: { super_admin: "write", admin: "write", view_only: "read", developer: "write", analyst: "write", identity_analyst: "write" },
  },
  {
    id: "identity_verification_operations_2",
    name: "identity_verification_operations",
    actions: "read, write",
    productCategory: "Compliance & Identity",
    taskCategory: "Handle customer issues",
    actionType: "Read + Write",
    sensitivityLevel: "Contains PII",
    description: "Identity verification",
    roleAccess: { super_admin: "write", admin: "write", view_only: "read", developer: "write", analyst: "write", identity_analyst: "write" },
  },
  {
    id: "climate_operations_1",
    name: "climate_operations",
    actions: "read, write",
    productCategory: "Crypto & Climate",
    taskCategory: "Process transactions",
    actionType: "Read + Write",
    sensitivityLevel: "Non-sensitive",
    description: "Climate orders",
    roleAccess: { super_admin: "write", admin: "write", view_only: "read", developer: "write", analyst: "write" },
  },
  {
    id: "climate_operations_2",
    name: "climate_operations",
    actions: "read, write",
    productCategory: "Crypto & Climate",
    taskCategory: "Configure settings",
    actionType: "Read + Write",
    sensitivityLevel: "Non-sensitive",
    description: "Climate orders",
    roleAccess: { super_admin: "write", admin: "write", view_only: "read", developer: "write", analyst: "write" },
  },
  {
    id: "crypto_operations_1",
    name: "crypto_operations",
    actions: "read, write",
    productCategory: "Crypto & Climate",
    taskCategory: "Process transactions",
    actionType: "Read + Write",
    sensitivityLevel: "Non-sensitive",
    description: "Crypto financial accounts",
    roleAccess: { super_admin: "write", admin: "write", view_only: "read", developer: "write", analyst: "write" },
  },
  {
    id: "customer_operations_1",
    name: "customer_operations",
    actions: "read, write",
    productCategory: "Customers",
    taskCategory: "Handle customer issues",
    actionType: "Read + Write",
    sensitivityLevel: "Contains PII",
    description: "Manage customer profiles",
    roleAccess: { super_admin: "write", admin: "write", view_only: "read", developer: "write", support: "write", support_associate: "write", analyst: "write", refund_analyst: "read", dispute_analyst: "read" },
  },
  {
    id: "customer_operations_2",
    name: "customer_operations",
    actions: "read, write",
    productCategory: "Customers",
    taskCategory: "Export & analyze data",
    actionType: "Read + Write",
    sensitivityLevel: "Contains PII",
    description: "Manage customer profiles",
    roleAccess: { super_admin: "write", admin: "write", view_only: "read", developer: "write", support: "write", support_associate: "write", analyst: "write", refund_analyst: "read", dispute_analyst: "read" },
  },
  {
    id: "customer_portal_operations_1",
    name: "customer_portal_operations",
    actions: "write",
    productCategory: "Customers",
    taskCategory: "Configure settings",
    actionType: "Create & update",
    sensitivityLevel: "Non-sensitive",
    description: "Create customer portals",
    roleAccess: { super_admin: "write", admin: "write", analyst: "write" },
  },
  {
    id: "customer_portal_operations_2",
    name: "customer_portal_operations",
    actions: "write",
    productCategory: "Customers",
    taskCategory: "Handle customer issues",
    actionType: "Create & update",
    sensitivityLevel: "Non-sensitive",
    description: "Create customer portals",
    roleAccess: { super_admin: "write", admin: "write", analyst: "write" },
  },
  {
    id: "dispute_operations_1",
    name: "dispute_operations",
    actions: "read, write",
    productCategory: "Disputes & Fraud Prevention",
    taskCategory: "Handle customer issues",
    actionType: "Read + Write",
    sensitivityLevel: "Non-sensitive",
    description: "Manage disputes",
    roleAccess: { super_admin: "write", admin: "write", view_only: "read", developer: "write", support: "write", support_associate: "write", analyst: "write", refund_analyst: "read", dispute_analyst: "write" },
  },
  {
    id: "dispute_operations_2",
    name: "dispute_operations",
    actions: "read, write",
    productCategory: "Disputes & Fraud Prevention",
    taskCategory: "Manage disputes & fraud",
    actionType: "Read + Write",
    sensitivityLevel: "Non-sensitive",
    description: "Manage disputes",
    roleAccess: { super_admin: "write", admin: "write", view_only: "read", developer: "write", support: "write", support_associate: "write", analyst: "write", refund_analyst: "read", dispute_analyst: "write" },
  },
  {
    id: "radar_operations_1",
    name: "radar_operations",
    actions: "read, write",
    productCategory: "Disputes & Fraud Prevention",
    taskCategory: "Configure settings",
    actionType: "Read + Write",
    sensitivityLevel: "Non-sensitive",
    description: "Configure Radar fraud rules",
    roleAccess: { super_admin: "write", admin: "write", view_only: "read", developer: "write", support: "read", support_associate: "read", analyst: "read", refund_analyst: "read" },
  },
  {
    id: "radar_operations_2",
    name: "radar_operations",
    actions: "read, write",
    productCategory: "Disputes & Fraud Prevention",
    taskCategory: "Manage disputes & fraud",
    actionType: "Read + Write",
    sensitivityLevel: "Non-sensitive",
    description: "Configure Radar fraud rules",
    roleAccess: { super_admin: "write", admin: "write", view_only: "read", developer: "write", support: "read", support_associate: "read", analyst: "read", refund_analyst: "read" },
  },
  {
    id: "review_operations_1",
    name: "review_operations",
    actions: "write",
    productCategory: "Disputes & Fraud Prevention",
    taskCategory: "Handle customer issues",
    actionType: "Create & update",
    sensitivityLevel: "Non-sensitive",
    description: "Action fraud reviews",
    roleAccess: { super_admin: "write", admin: "write", support: "write", support_associate: "write", analyst: "write" },
  },
  {
    id: "review_operations_2",
    name: "review_operations",
    actions: "write",
    productCategory: "Disputes & Fraud Prevention",
    taskCategory: "Manage disputes & fraud",
    actionType: "Create & update",
    sensitivityLevel: "Non-sensitive",
    description: "Action fraud reviews",
    roleAccess: { super_admin: "write", admin: "write", support: "write", support_associate: "write", analyst: "write" },
  },
  {
    id: "balance_operations_1",
    name: "balance_operations",
    actions: "read",
    productCategory: "Financial Operations",
    taskCategory: "Monitor financials",
    actionType: "Read-only",
    sensitivityLevel: "Financial data",
    description: "View account balances",
    roleAccess: { super_admin: "read", admin: "read", view_only: "read", support: "read", support_associate: "read", analyst: "read", refund_analyst: "read", dispute_analyst: "read" },
  },
  {
    id: "balance_operations_2",
    name: "balance_operations",
    actions: "read",
    productCategory: "Financial Operations",
    taskCategory: "Export & analyze data",
    actionType: "Read-only",
    sensitivityLevel: "Financial data",
    description: "View account balances",
    roleAccess: { super_admin: "read", admin: "read", view_only: "read", support: "read", support_associate: "read", analyst: "read", refund_analyst: "read", dispute_analyst: "read" },
  },
  {
    id: "balance_transfer_operations_1",
    name: "balance_transfer_operations",
    actions: "write",
    productCategory: "Financial Operations",
    taskCategory: "Transfer funds",
    actionType: "Destructive",
    sensitivityLevel: "Financial data",
    description: "Transfer balances (high risk)",
    roleAccess: { super_admin: "write", admin: "write", analyst: "write" },
  },
  {
    id: "payout_operations_1",
    name: "payout_operations",
    actions: "read, write",
    productCategory: "Financial Operations",
    taskCategory: "Transfer funds",
    actionType: "Read + Write",
    sensitivityLevel: "Financial data",
    description: "Manage payouts",
    roleAccess: { super_admin: "write", admin: "write", view_only: "read", analyst: "write" },
  },
  {
    id: "payout_operations_2",
    name: "payout_operations",
    actions: "read, write",
    productCategory: "Financial Operations",
    taskCategory: "Monitor financials",
    actionType: "Read + Write",
    sensitivityLevel: "Financial data",
    description: "Manage payouts",
    roleAccess: { super_admin: "write", admin: "write", view_only: "read", analyst: "write" },
  },
  {
    id: "transfer_operations_1",
    name: "transfer_operations",
    actions: "read, write",
    productCategory: "Financial Operations",
    taskCategory: "Transfer funds",
    actionType: "Read + Write",
    sensitivityLevel: "Financial data",
    description: "Transfer operations",
    roleAccess: { super_admin: "write", admin: "write", view_only: "read", analyst: "write" },
  },
  {
    id: "transfer_operations_2",
    name: "transfer_operations",
    actions: "read, write",
    productCategory: "Financial Operations",
    taskCategory: "Monitor financials",
    actionType: "Read + Write",
    sensitivityLevel: "Financial data",
    description: "Transfer operations",
    roleAccess: { super_admin: "write", admin: "write", view_only: "read", analyst: "write" },
  },
  {
    id: "data_export_operations_1",
    name: "data_export_operations",
    actions: "read",
    productCategory: "Integrations & Data",
    taskCategory: "Export & analyze data",
    actionType: "Read-only",
    sensitivityLevel: "Financial data + PII",
    description: "Export bulk data",
    roleAccess: { super_admin: "read", admin: "read", view_only: "read", developer: "read", analyst: "read" },
  },
  {
    id: "dev_integration_1",
    name: "dev_integration",
    actions: "read, write",
    productCategory: "Integrations & Data",
    taskCategory: "Develop & integrate",
    actionType: "Read + Write",
    sensitivityLevel: "Non-sensitive",
    description: "Development tools",
    roleAccess: { super_admin: "write", admin: "write", view_only: "read", developer: "write", analyst: "write" },
  },
  {
    id: "reporting_operations_1",
    name: "reporting_operations",
    actions: "read, write",
    productCategory: "Integrations & Data",
    taskCategory: "Export & analyze data",
    actionType: "Read + Write",
    sensitivityLevel: "Financial data",
    description: "Run and access reports",
    roleAccess: { super_admin: "write", admin: "write", view_only: "read, write", developer: "write", support: "write", support_associate: "write", analyst: "write", refund_analyst: "read" },
  },
  {
    id: "reporting_operations_2",
    name: "reporting_operations",
    actions: "read, write",
    productCategory: "Integrations & Data",
    taskCategory: "Monitor financials",
    actionType: "Read + Write",
    sensitivityLevel: "Financial data",
    description: "Run and access reports",
    roleAccess: { super_admin: "write", admin: "write", view_only: "read, write", developer: "write", support: "write", support_associate: "write", analyst: "write", refund_analyst: "read" },
  },
  {
    id: "stripe_apps_development_1",
    name: "stripe_apps_development",
    actions: "read, write",
    productCategory: "Integrations & Data",
    taskCategory: "Develop & integrate",
    actionType: "Read + Write",
    sensitivityLevel: "Non-sensitive",
    description: "Build Stripe Apps",
    roleAccess: { super_admin: "write", admin: "write", view_only: "read", developer: "write", analyst: "write" },
  },
  {
    id: "issuing_card_operations_1",
    name: "issuing_card_operations",
    actions: "read, write",
    productCategory: "Issuing & Cards",
    taskCategory: "Handle customer issues",
    actionType: "Read + Write",
    sensitivityLevel: "Payment credentials",
    description: "Manage issuing cards",
    roleAccess: { super_admin: "write", admin: "write", view_only: "read", support: "write", support_associate: "read, write", analyst: "write" },
  },
  {
    id: "issuing_card_operations_2",
    name: "issuing_card_operations",
    actions: "read, write",
    productCategory: "Issuing & Cards",
    taskCategory: "Manage cards",
    actionType: "Read + Write",
    sensitivityLevel: "Payment credentials",
    description: "Manage issuing cards",
    roleAccess: { super_admin: "write", admin: "write", view_only: "read", support: "write", support_associate: "read, write", analyst: "write" },
  },
  {
    id: "charge_1",
    name: "charge",
    actions: "read",
    productCategory: "Payments",
    taskCategory: "Handle customer issues",
    actionType: "Read-only",
    sensitivityLevel: "Non-sensitive",
    description: "Charge read access",
    roleAccess: { view_only: "read", refund_analyst: "read", dispute_analyst: "read" },
  },
  {
    id: "charge_2",
    name: "charge",
    actions: "read",
    productCategory: "Payments",
    taskCategory: "Export & analyze data",
    actionType: "Read-only",
    sensitivityLevel: "Non-sensitive",
    description: "Charge read access",
    roleAccess: { view_only: "read", refund_analyst: "read", dispute_analyst: "read" },
  },
  {
    id: "charge_operations_1",
    name: "charge_operations",
    actions: "write",
    productCategory: "Payments",
    taskCategory: "Handle customer issues",
    actionType: "Create & update",
    sensitivityLevel: "Financial data",
    description: "Process charges and refunds",
    roleAccess: { super_admin: "write", admin: "write", developer: "write", support: "write", support_associate: "write", analyst: "write" },
  },
  {
    id: "charge_operations_2",
    name: "charge_operations",
    actions: "write",
    productCategory: "Payments",
    taskCategory: "Process transactions",
    actionType: "Create & update",
    sensitivityLevel: "Financial data",
    description: "Process charges and refunds",
    roleAccess: { super_admin: "write", admin: "write", developer: "write", support: "write", support_associate: "write", analyst: "write" },
  },
  {
    id: "payment_intent_1",
    name: "payment_intent",
    actions: "read",
    productCategory: "Payments",
    taskCategory: "Handle customer issues",
    actionType: "Read-only",
    sensitivityLevel: "Non-sensitive",
    description: "Payment intent read",
    roleAccess: { view_only: "read", refund_analyst: "read", dispute_analyst: "read" },
  },
  {
    id: "payment_intent_2",
    name: "payment_intent",
    actions: "read",
    productCategory: "Payments",
    taskCategory: "Export & analyze data",
    actionType: "Read-only",
    sensitivityLevel: "Non-sensitive",
    description: "Payment intent read",
    roleAccess: { view_only: "read", refund_analyst: "read", dispute_analyst: "read" },
  },
  {
    id: "payment_intent_operations_1",
    name: "payment_intent_operations",
    actions: "write",
    productCategory: "Payments",
    taskCategory: "Handle customer issues",
    actionType: "Create & update",
    sensitivityLevel: "Non-sensitive",
    description: "Manage payment intents",
    roleAccess: { super_admin: "write", admin: "write", developer: "write", support: "write", support_associate: "write", analyst: "write" },
  },
  {
    id: "payment_intent_operations_2",
    name: "payment_intent_operations",
    actions: "write",
    productCategory: "Payments",
    taskCategory: "Process transactions",
    actionType: "Create & update",
    sensitivityLevel: "Non-sensitive",
    description: "Manage payment intents",
    roleAccess: { super_admin: "write", admin: "write", developer: "write", support: "write", support_associate: "write", analyst: "write" },
  },
  {
    id: "payment_processing_1",
    name: "payment_processing",
    actions: "read, write",
    productCategory: "Payments",
    taskCategory: "Process transactions",
    actionType: "Read + Write",
    sensitivityLevel: "Payment credentials",
    description: "Manage payment methods",
    roleAccess: { super_admin: "write", admin: "write", view_only: "read", developer: "write", support: "write", support_associate: "write", analyst: "write", refund_analyst: "read", dispute_analyst: "read" },
  },
  {
    id: "payment_processing_2",
    name: "payment_processing",
    actions: "read, write",
    productCategory: "Payments",
    taskCategory: "Configure settings",
    actionType: "Read + Write",
    sensitivityLevel: "Payment credentials",
    description: "Manage payment methods",
    roleAccess: { super_admin: "write", admin: "write", view_only: "read", developer: "write", support: "write", support_associate: "write", analyst: "write", refund_analyst: "read", dispute_analyst: "read" },
  },
  {
    id: "checkout_operations_1",
    name: "checkout_operations",
    actions: "read, write",
    productCategory: "Products & Orders",
    taskCategory: "Process transactions",
    actionType: "Read + Write",
    sensitivityLevel: "Non-sensitive",
    description: "Manage checkout",
    roleAccess: { super_admin: "write", admin: "write", view_only: "read", developer: "write", support: "write", support_associate: "read", analyst: "write" },
  },
  {
    id: "checkout_operations_2",
    name: "checkout_operations",
    actions: "read, write",
    productCategory: "Products & Orders",
    taskCategory: "Configure settings",
    actionType: "Read + Write",
    sensitivityLevel: "Non-sensitive",
    description: "Manage checkout",
    roleAccess: { super_admin: "write", admin: "write", view_only: "read", developer: "write", support: "write", support_associate: "read", analyst: "write" },
  },
  {
    id: "order_operations_1",
    name: "order_operations",
    actions: "read, write",
    productCategory: "Products & Orders",
    taskCategory: "Handle customer issues",
    actionType: "Read + Write",
    sensitivityLevel: "Non-sensitive",
    description: "Manage orders",
    roleAccess: { super_admin: "write", admin: "write", view_only: "read", developer: "write", support: "write", support_associate: "write", analyst: "write", refund_analyst: "read", dispute_analyst: "read" },
  },
  {
    id: "order_operations_2",
    name: "order_operations",
    actions: "read, write",
    productCategory: "Products & Orders",
    taskCategory: "Process transactions",
    actionType: "Read + Write",
    sensitivityLevel: "Non-sensitive",
    description: "Manage orders",
    roleAccess: { super_admin: "write", admin: "write", view_only: "read", developer: "write", support: "write", support_associate: "write", analyst: "write", refund_analyst: "read", dispute_analyst: "read" },
  },
  {
    id: "order_refund_operations_1",
    name: "order_refund_operations",
    actions: "write",
    productCategory: "Products & Orders",
    taskCategory: "Handle customer issues",
    actionType: "Create & update",
    sensitivityLevel: "Financial data",
    description: "Process order refunds",
    roleAccess: { super_admin: "write", admin: "write", analyst: "write", refund_analyst: "write" },
  },
  {
    id: "product_operations_1",
    name: "product_operations",
    actions: "read, write",
    productCategory: "Products & Orders",
    taskCategory: "Manage catalog",
    actionType: "Read + Write",
    sensitivityLevel: "Non-sensitive",
    description: "Manage products and pricing",
    roleAccess: { super_admin: "write", admin: "write", view_only: "read", support: "write", support_associate: "read", analyst: "write", refund_analyst: "read", dispute_analyst: "read" },
  },
  {
    id: "product_operations_2",
    name: "product_operations",
    actions: "read, write",
    productCategory: "Products & Orders",
    taskCategory: "Configure settings",
    actionType: "Read + Write",
    sensitivityLevel: "Non-sensitive",
    description: "Manage products and pricing",
    roleAccess: { super_admin: "write", admin: "write", view_only: "read", support: "write", support_associate: "read", analyst: "write", refund_analyst: "read", dispute_analyst: "read" },
  },
  {
    id: "promotion_operations_1",
    name: "promotion_operations",
    actions: "read, write",
    productCategory: "Products & Orders",
    taskCategory: "Manage catalog",
    actionType: "Read + Write",
    sensitivityLevel: "Non-sensitive",
    description: "Manage promotions",
    roleAccess: { super_admin: "write", admin: "write", view_only: "read", developer: "write", support: "write", support_associate: "write", analyst: "write" },
  },
  {
    id: "promotion_operations_2",
    name: "promotion_operations",
    actions: "read, write",
    productCategory: "Products & Orders",
    taskCategory: "Configure settings",
    actionType: "Read + Write",
    sensitivityLevel: "Non-sensitive",
    description: "Manage promotions",
    roleAccess: { super_admin: "write", admin: "write", view_only: "read", developer: "write", support: "write", support_associate: "write", analyst: "write" },
  },
  {
    id: "dashboard_baseline_1",
    name: "dashboard_baseline",
    actions: "read",
    productCategory: "Support & Operations",
    taskCategory: "All tasks",
    actionType: "Read-only",
    sensitivityLevel: "Non-sensitive",
    description: "Basic Dashboard access (required)",
    roleAccess: { super_admin: "read", admin: "read", view_only: "read", developer: "read", support: "read", support_associate: "read", analyst: "read", refund_analyst: "read", dispute_analyst: "read", issuing_support_agent: "read", tax_analyst: "read", identity_analyst: "read", iam_admin: "read", sandbox_admin: "read" },
  },
  {
    id: "settings_security_1",
    name: "settings_security",
    actions: "write",
    productCategory: "Support & Operations",
    taskCategory: "Configure settings",
    actionType: "Administrative",
    sensitivityLevel: "Payment credentials",
    description: "Security configuration",
    roleAccess: { iam_admin: "write" },
  },
  {
    id: "settings_security_2",
    name: "settings_security",
    actions: "write",
    productCategory: "Support & Operations",
    taskCategory: "Manage team access",
    actionType: "Administrative",
    sensitivityLevel: "Payment credentials",
    description: "Security configuration",
    roleAccess: { iam_admin: "write" },
  },
  {
    id: "tax_automation_operations_1",
    name: "tax_automation_operations",
    actions: "read, write",
    productCategory: "Tax",
    taskCategory: "Configure settings",
    actionType: "Read + Write",
    sensitivityLevel: "Non-sensitive",
    description: "Tax automation rules",
    roleAccess: { super_admin: "write", admin: "write", view_only: "read", developer: "write", support: "write", analyst: "write" },
  },
  {
    id: "tax_automation_operations_2",
    name: "tax_automation_operations",
    actions: "read, write",
    productCategory: "Tax",
    taskCategory: "Monitor tax compliance",
    actionType: "Read + Write",
    sensitivityLevel: "Non-sensitive",
    description: "Tax automation rules",
    roleAccess: { super_admin: "write", admin: "write", view_only: "read", developer: "write", support: "write", analyst: "write" },
  },
  {
    id: "tax_filing_operations_1",
    name: "tax_filing_operations",
    actions: "read, write",
    productCategory: "Tax",
    taskCategory: "Configure settings",
    actionType: "Read + Write",
    sensitivityLevel: "Financial data + PII",
    description: "Tax filing management",
    roleAccess: { super_admin: "write", admin: "write", view_only: "read", developer: "read", analyst: "write" },
  },
  {
    id: "tax_filing_operations_2",
    name: "tax_filing_operations",
    actions: "read, write",
    productCategory: "Tax",
    taskCategory: "Monitor tax compliance",
    actionType: "Read + Write",
    sensitivityLevel: "Financial data + PII",
    description: "Tax filing management",
    roleAccess: { super_admin: "write", admin: "write", view_only: "read", developer: "read", analyst: "write" },
  },
  {
    id: "terminal_infrastructure_1",
    name: "terminal_infrastructure",
    actions: "read",
    productCategory: "Terminal",
    taskCategory: "Monitor hardware",
    actionType: "Read-only",
    sensitivityLevel: "Non-sensitive",
    description: "View terminal infrastructure",
    roleAccess: { super_admin: "read", admin: "read", view_only: "read", support: "read", support_associate: "read", analyst: "read" },
  },
  {
    id: "terminal_operations_1",
    name: "terminal_operations",
    actions: "write",
    productCategory: "Terminal",
    taskCategory: "Manage hardware",
    actionType: "Create & update",
    sensitivityLevel: "Non-sensitive",
    description: "Terminal POS operations",
    roleAccess: { super_admin: "write", admin: "write", analyst: "write" },
  },
  {
    id: "terminal_operations_2",
    name: "terminal_operations",
    actions: "write",
    productCategory: "Terminal",
    taskCategory: "Process transactions",
    actionType: "Create & update",
    sensitivityLevel: "Non-sensitive",
    description: "Terminal POS operations",
    roleAccess: { super_admin: "write", admin: "write", analyst: "write" },
  },
];

// Helper to get unique values for grouping
export const productCategories = [...new Set(permissions.map((p) => p.productCategory))].sort();
export const taskCategories = [...new Set(permissions.map((p) => p.taskCategory))].sort();
export const actionTypes = [...new Set(permissions.map((p) => p.actionType))].sort();

// Get permissions for a specific role
export function getPermissionsForRole(roleId: string): Permission[] {
  return permissions.filter((p) => p.roleAccess[roleId]);
}

// Get unique permissions for a role (deduplicated by name)
export function getUniquePermissionsForRole(roleId: string): Permission[] {
  const rolePerms = getPermissionsForRole(roleId);
  const seen = new Set<string>();
  return rolePerms.filter((p) => {
    if (seen.has(p.name)) return false;
    seen.add(p.name);
    return true;
  });
}

// Group permissions by a field
export function groupPermissions(
  perms: Permission[],
  groupBy: "productCategory" | "taskCategory" | "actionType"
): Record<string, Permission[]> {
  const groups: Record<string, Permission[]> = {};
  for (const p of perms) {
    const key = p[groupBy];
    if (!groups[key]) groups[key] = [];
    groups[key].push(p);
  }
  return groups;
}

